### ISSUE TITLE
No module named 'serial'

### ISSUE THREAD

**Issue by AM3FS** [armel/ICUSBProxy#11]
Hi Armel. I've hit a problem with running ICUSBProxy.PY on my PC...
I've Python 3.10.4 installed, but it appears the serial module is not part of the distro.

This was the error...
Traceback (most recent call last):
  File "C:\Amateur Radio\GIT\ICUSBProxy v0.0.5\ICUSBProxy\ICUSBProxy.py", line 11, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

So I installed PYserial 3.5

The 'no module error' went, now I can start the proxy
"Starting ICUSBProxy v0.0.5 HTTPD on Port 1234"

I'm now seeing strange results such as random numbers as a frequency. 
It seems to connect but does not function as it should.

Is this PYserial a suitable replacement for the serial module?  pypi.org/project/pyserial/

Thanks
Andrew

**Comment by armel** [comment]
Hi Andrew,

This is probably a CI-V issue with your transceiver settings.
Please, check on your transceiver : 

Connectors > CI-V > CI-V USB Port       Unlink from [REMOTE]
Connectors > CI-V > CI-V USB Baud Rate  115200
Connectors > CI-V > CI-V USB Echo Back  OFF

Armel F4HWN

**Comment by AM3FS** [comment]
Hi Armel, yes both the 9700 and 7300 have the same symptoms, and I've double-checked the settings in both radios. The 705 works flawlessly on BT. Great software by the way too Armel. I did get it working by power cycling everything :) Andrew. VK3FS

**Comment by armel** [comment]
Ok Andrew.
And what about CI_V_ADDRESS in settings.h ? By default, this is 0xA4 on IC-705. But on IC-7300, this is 0x94.

Armel F4HWN.

**Comment by AM3FS** [comment]
Hi Armel,

All sorted. A power cycle of radios and PCs did the trick. Thanks for your help.
Cheers
Andrew
![IC-7300 Stack 1364](https://user-images.githubusercontent.com/105627097/168613074-6f6cc041-f60e-4ebc-a412-1ea664c64b62.JPG)

**Comment by armel** [comment]
Nice job Andrew 👍
