### ISSUE TITLE
Not working IC9700

### ISSUE THREAD

**Issue by Vito6** [armel/ICUSBProxy#9]
Hi All installed but M5stack show "check proxy" and don't connect. What can I check?

**Comment by armel** [comment]
Hi,

ICUSBProxy is running ?
Wifi is well configured on the M5Stack ?
ICUSBProxy is installed on your PC ? This PC is on the same local network ?
Of course, your M5Stack and ICUSBProxy need to run on the same local network. 

Armel.

**Comment by Vito6** [comment]
ICUSBProxy is running ? yes
Wifi is well configured on the M5Stack ? yes it is connected via wifi (I see it in my router connections panel)
ICUSBProxy is installed on your PC ? This PC is on the same local network ? Yes
Of course, your M5Stack and ICUSBProxy need to run on the same local network

![screenshot 849](https://user-images.githubusercontent.com/32937699/166205923-b308b76c-5f61-4569-9b14-d6555212e7a9.jpg)
![screenshot 851](https://user-images.githubusercontent.com/32937699/166206240-e50dff49-e8c8-4fe9-93a7-50e5934db790.jpg)

My 9700 has 2 com ports (COM9 and COM 13), I have tried both.
Thanks for your help Armel.

Vito

**Comment by armel** [comment]
Hi Vito,

Ok. Next question. In settings.h, I see that line 20, PROXY_URL is set to default value (http://192.168.1.32).
Local IP Address of your PC on where ICUSBProxy is running is 192.168.1.32 ? If not, change this. For example, if local IP Address of your PC is 192.168.1.4, set PROXY_URL to "http://192.168.1.4".

Regards,

Armel.

**Comment by Vito6** [comment]
oh... I'm stupid.
Now I set the correct IP but now I see Check TX and other icons.. :

![screenshot 852](https://user-images.githubusercontent.com/32937699/166236254-284d397e-4366-479e-ad8f-8b4ef1795b59.jpg)
:(

**Comment by armel** [comment]
Ok.
Your IC-9700 is up and connected to your PC on COM13 via USB cable ?
What about CI-V settings on your IC-9700 ?

Connectors > CI-V > CI-V USB Port       Unlink from [REMOTE]
Connectors > CI-V > CI-V USB Baud Rate  115200
Connectors > CI-V > CI-V USB Echo Back  OFF

Armel.

**Comment by Vito6** [comment]
Yes is connected via usb on COM13 (but there is another COM9 in device settings on pc) 
The CI-v is A2H and the settings are the same

**Comment by armel** [comment]
A2H ? So you need to change line 11 to 0xA2 (not 0x2A...).

Armel.

**Comment by Vito6** [comment]
Yes I know I just correct but not work :(

**Comment by Vito6** [comment]
![screenshot 853](https://user-images.githubusercontent.com/32937699/166239241-581f36f2-3d35-42aa-af53-56daf75d12e1.jpg)

**Comment by armel** [comment]
Hummm too many changes since the beginning. 
You really need to check all these settings.
If PROXY_URL, SERIAL_DEVICE, CI_V_ADDRESS, etc. is not good, sure, it will not work. 
So check again, and check your CI-V settings in your Transceiver. 
Finally restart your M5Stack and restart your ICUSBProxy.

By the way, what do you obtain if, with your PC browser (for example, Chrome), you go on :  

http://192.168.1.103:1234/?civ=fe,fe,a2,e0,03,fd,115200,COM3

Armel.

**Comment by Vito6** [comment]
This is the message:

HTTP/1.0 200 OK Server: BaseHTTP/0.6 Python/3.10.4 Date: Mon, 02 May 2022 13:36:20 GMT Content-type: text/html

Why COM3?

The settings are those of the last screen

**Comment by armel** [comment]
COM9

**Comment by Vito6** [comment]
with COM9 white page.
I have tried with the other 9700 COM13 and the answer is:

fefee0a2030075784501fd

**Comment by Vito6** [comment]
Hey Armel, don't ask me how but now that I have changed COM13 (I done this also in the past) and.... WORKS!
Thanks!

**Comment by armel** [comment]
Good job 👍 
Ok, so your SERIAL_DEVICE is COM13.
I will close this problem.

Armel.

**Comment by Vito6** [comment]
thanks a lot!

Vito

**Comment by armel** [comment]
You're welcome.
